
# 
# 
# 

version: '1.0'

# 
# TYPES
# 

types:

  Service:
    name: Service
    version: 1
    implements:
      - "#Deployable"
      - "#Runnable"
      - "#Accessible"
    property:
      name: string
      description: string
      pcol: string
      port: string
      path: string
      host: "#Machine"
      alias: "#MachineAlias"
      connections:
        - "#Connection"
    required:
      - name

  ServiceGroup:
    name: ServiceGroup
    version: 1
    property:
      name: string
      description: string
      members:
        - "#Service"
    required:
      - name
      - description
