
# 
# K8s nginx compose
# 

version: '1.0'
name: kubernetes/kubernetes-service.yml

# 
# TYPES
# 

types:

  KubernetesService:
    name: KubernetesService
    version: 1
    property:
      name: string
      apiVersion: "#KubernetesAPIVersion"
      # metadataName: string
      # metadataNamespace: "#KubernetesNamespace"
      # metadataApp: "#KubernetesApp"
      # metadataAppLabel: "#KubernetesAppLabel"
      # metadataEnvironmentLabel: "#KubernetesEnvironmentLabel"
      # metadataReleaseLabel: "#KubernetesReleaseLabel"
      # metadataRoleLabel: "#KubernetesRoleLabel"
      metadata: "#KubernetesMetadata"
      spec: "#KubernetesServiceSpec"

  KubernetesServiceSpec:
    name: KubernetesServiceSpec
    version: 1
    extends: "#KubernetesSpec"
    property:
      name: string
      # app: "#KubernetesApp"
      ports:
        - "#KubernetesServicePort"
      # matchApp: "#KubernetesApp"
      # matchLabels:
      #   - "#KubernetesLabel"

  KubernetesServicePort:
    name: KubernetesServicePort
    version: 1
    property:
      name: string
      protocol: string
      port: "#Port"
      targetPort: "#Port"
    required:
      - name
      - protocol
      - port
      - targetPort
