
# 
# K8s nginx compose
# 

version: '1.0'
name: kubernetes/kubernetes-container.yml

# 
# TYPES
# 

types:

  KubernetesContainer:
    name: KubernetesContainer
    version: 1
    property:
      name: string
      displayName: string
      image: "#ContainerImage"
      ports:
        - "#ContainerPort"
      volumes:
        - "#KubernetesVolume"
