
# 
# K8s nginx compose
# 

version: '1.0'
name: kubernetes/kubernetes-metadata.yml

# 
# TYPES
# 

types:

  KubernetesMetadata:
    name: KubernetesMetadata
    version: 1
    property:
      name: string
      displayName: string
      namespace: "#KubernetesNamespace"
      app: "#KubernetesApp"
      appLabel: "#KubernetesAppLabel"
      environmentLabel: "#KubernetesEnvironmentLabel"
      releaseLabel: "#KubernetesReleaseLabel"
      roleLabel: "#KubernetesRoleLabel"
      # labels: 
      #   - "#KubernetesLabel"
      labels: 
        - "#LabelSelector"
