
# 
# K8s nginx compose
# 

version: '1.0'
name: kubernetes/kubernetes-persistent-volume.yml

# 
# TYPES
# 

types:

  KubernetesPersistentVolumeClaim:
    name: KubernetesPersistentVolumeClaim
    version: 1
    property:
      name: string
      apiVersion: "#KubernetesAPIVersion"
      # metadataName: string
      # metadataNamespace: "#KubernetesNamespace"
      # metadataApp: "#KubernetesApp"
      # metadataAppLabel: "#KubernetesAppLabel"
      # metadataEnvironmentLabel: "#KubernetesEnvironmentLabel"
      # metadataReleaseLabel: "#KubernetesReleaseLabel"
      # metadataRoleLabel: "#KubernetesRoleLabel"
      metadata: "#KubernetesMetadata"
      spec: "#KubernetesPersistentVolumeClaimSpec"

  KubernetesPersistentVolumeClaimSpec:
    name: KubernetesPersistentVolumeClaimSpec
    version: 1
    extends: "#KubernetesSpec"
    property:
      name: string
      accessModes:
        - "#KubernetesAccessMode"
      storageClass: "#KubernetesStorageClass"
      storageSize: string
      # matchApp: "#KubernetesApp"
      # matchLabels:
      #   - "#KubernetesLabel"
