
# 
# K8s nginx compose
# 

version: '1.0'
name: kubernetes/kubernetes-config.yml

# 
# TYPES
# 

types:

  KubernetesConfig:
    name: KubernetesConfig
    version: 1
    property:
      name: string
      apiVersion: "#KubernetesAPIVersion"
      clusters:
        - "#KubernetesCluster"
      users:
        - "#KubernetesUser"
      contexts:
        - "#KubernetesContext"
      currentContext: "#KubernetesContext"
