
# 
# K8s nginx compose
# 

version: '1.0'
name: kubernetes/kubernetes-list.yml

# 
# TYPES
# 

types:

  KubernetesList:
    name: KubernetesList
    version: 1
    property:
      name: string
      displayName: string
      apiVersion: "#KubernetesAPIVersion"
      # metadataName: string
      # metadataNamespace: "#KubernetesNamespace"
      # metadataApp: "#KubernetesApp"
      # metadataAppLabel: "#KubernetesAppLabel"
      # metadataEnvironmentLabel: "#KubernetesEnvironmentLabel"
      # metadataReleaseLabel: "#KubernetesReleaseLabel"
      # metadataRoleLabel: "#KubernetesRoleLabel"
      metadata: "#KubernetesMetadata"
      deploymentItems:
        - "#KubernetesDeployment"
      serviceItems:
        - "#KubernetesService"
      ingressItems:
        - "#KubernetesIngress"
