
# 
# K8s nginx compose
# 

version: '1.0'
name: kubernetes/kubernetes-api-version.yml

# 
# TYPES
# 

types:

  KubernetesAPIVersion:
    name: KubernetesAPIVersion
    version: 1
    property:
      name: string
      apiVersion: string
